name: Security Check

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        
    - name: Run security scan
      run: |
        echo "Running security scan..."
        bandit -r . -ll -x tests/,docs/,.git/,__pycache__/,.venv/,venv/,build/,dist/ --skip B101
        echo "Security scan passed - no high/medium severity issues found"